Update README.md
brillout/awesome-react-components pull request #355
Opened 2022-06-30 17:14 UTC by albcunha

Added Echarts for react.

2022-06-30 17:16 UTC, bluepeter requested changes
Fix link

2023-04-21 01:00 UTC, Chethan30 commented
#397 Fixed here

2023-04-21 01:07 UTC, Chethan30 commented
#397

2023-08-17 15:32 UTC, im-zack commented
❤

2023-12-27 15:12 UTC, closed without merging